name: build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.bump.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: graalvm
          cache: maven

      - name: Build native executable
        run: ./mvnw package -Pnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=graalvm

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: backend-${{ inputs.version }}
          path: target/backend-${{ inputs.version }}-runner

  publish:
    needs: build
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}