name: publish

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: backend-${{ inputs.version }}
          path: target

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: src/main/docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            rafaelnds/backend:latest
            rafaelnds/backend:${{ inputs.version }}

#      - name: Trigger Deploy
#        if: success()
#        uses: peter-evans/repository-dispatch@v1
#        with:
#          token: ${{ secrets.PAT_TOKEN }}
#          repository: rafaelnsantos/deploy-backend
#          event-type: deploy
#          client-payload: '{"version": "${{ inputs.version }}"}'