## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu
          cache: maven

      - name: Build
        run: ./mvnw clean verify

  build:
    needs: test
    uses: ./.github/workflows/build.yml
    secrets: inherit
    with:
      version: ${{inputs.version}}